package com.zimerick.zmrklibrary.zmrkdatasync;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZMRKCORE_DATA_QUEUE_OBJECT.
 */
public class ZMRKCoreDataQueueObject {

    private Long objectID;
    private Integer appIndex;
    private String data;
    private Integer modifiedIndex;

    public ZMRKCoreDataQueueObject() {
    }

    public ZMRKCoreDataQueueObject(Long objectID) {
        this.objectID = objectID;
    }

    public ZMRKCoreDataQueueObject(Long objectID, Integer appIndex, String data, Integer modifiedIndex) {
        this.objectID = objectID;
        this.appIndex = appIndex;
        this.data = data;
        this.modifiedIndex = modifiedIndex;
    }

    public Long getObjectID() {
        return objectID;
    }

    public void setObjectID(Long objectID) {
        this.objectID = objectID;
    }

    public Integer getAppIndex() {
        return appIndex;
    }

    public void setAppIndex(Integer appIndex) {
        this.appIndex = appIndex;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Integer getModifiedIndex() {
        return modifiedIndex;
    }

    public void setModifiedIndex(Integer modifiedIndex) {
        this.modifiedIndex = modifiedIndex;
    }

}
