package com.nqmtuan.android.randomrandomizer;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.nqmtuan.android.randomrandomizer.RandomElement;
import com.nqmtuan.android.randomrandomizer.RandomElementCollection;

import com.nqmtuan.android.randomrandomizer.RandomElementDao;
import com.nqmtuan.android.randomrandomizer.RandomElementCollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig randomElementDaoConfig;
    private final DaoConfig randomElementCollectionDaoConfig;

    private final RandomElementDao randomElementDao;
    private final RandomElementCollectionDao randomElementCollectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        randomElementDaoConfig = daoConfigMap.get(RandomElementDao.class).clone();
        randomElementDaoConfig.initIdentityScope(type);

        randomElementCollectionDaoConfig = daoConfigMap.get(RandomElementCollectionDao.class).clone();
        randomElementCollectionDaoConfig.initIdentityScope(type);

        randomElementDao = new RandomElementDao(randomElementDaoConfig, this);
        randomElementCollectionDao = new RandomElementCollectionDao(randomElementCollectionDaoConfig, this);

        registerDao(RandomElement.class, randomElementDao);
        registerDao(RandomElementCollection.class, randomElementCollectionDao);
    }
    
    public void clear() {
        randomElementDaoConfig.getIdentityScope().clear();
        randomElementCollectionDaoConfig.getIdentityScope().clear();
    }

    public RandomElementDao getRandomElementDao() {
        return randomElementDao;
    }

    public RandomElementCollectionDao getRandomElementCollectionDao() {
        return randomElementCollectionDao;
    }

}
