package com.nqmtuan.android.randomrandomizer;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.nqmtuan.android.randomrandomizer.RandomElement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RANDOM_ELEMENT.
*/
public class RandomElementDao extends AbstractDao<RandomElement, Long> {

    public static final String TABLENAME = "RANDOM_ELEMENT";

    /**
     * Properties of entity RandomElement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property ImageName = new Property(2, String.class, "imageName", false, "IMAGE_NAME");
        public final static Property CollectionId = new Property(3, Long.class, "collectionId", false, "COLLECTION_ID");
    };

    private DaoSession daoSession;

    private Query<RandomElement> randomElementCollection_ListElementsQuery;

    public RandomElementDao(DaoConfig config) {
        super(config);
    }
    
    public RandomElementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RANDOM_ELEMENT' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'IMAGE_NAME' TEXT," + // 2: imageName
                "'COLLECTION_ID' INTEGER);"); // 3: collectionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RANDOM_ELEMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RandomElement entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String imageName = entity.getImageName();
        if (imageName != null) {
            stmt.bindString(3, imageName);
        }
 
        Long collectionId = entity.getCollectionId();
        if (collectionId != null) {
            stmt.bindLong(4, collectionId);
        }
    }

    @Override
    protected void attachEntity(RandomElement entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RandomElement readEntity(Cursor cursor, int offset) {
        RandomElement entity = new RandomElement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imageName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // collectionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RandomElement entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImageName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCollectionId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RandomElement entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RandomElement entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "listElements" to-many relationship of RandomElementCollection. */
    public synchronized List<RandomElement> _queryRandomElementCollection_ListElements(Long collectionId) {
        if (randomElementCollection_ListElementsQuery == null) {
            QueryBuilder<RandomElement> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.CollectionId.eq(collectionId));
            randomElementCollection_ListElementsQuery = queryBuilder.build();
        } else {
            randomElementCollection_ListElementsQuery.setParameter(0, collectionId);
        }
        return randomElementCollection_ListElementsQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRandomElementCollectionDao().getAllColumns());
            builder.append(" FROM RANDOM_ELEMENT T");
            builder.append(" LEFT JOIN RANDOM_ELEMENT_COLLECTION T0 ON T.'COLLECTION_ID'=T0.'ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RandomElement loadCurrentDeep(Cursor cursor, boolean lock) {
        RandomElement entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        RandomElementCollection collection = loadCurrentOther(daoSession.getRandomElementCollectionDao(), cursor, offset);
        entity.setCollection(collection);

        return entity;    
    }

    public RandomElement loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RandomElement> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RandomElement> list = new ArrayList<RandomElement>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RandomElement> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RandomElement> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
