package com.nqmtuan.android.randomrandomizer;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.nqmtuan.android.randomrandomizer.RandomElementCollection;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RANDOM_ELEMENT_COLLECTION.
*/
public class RandomElementCollectionDao extends AbstractDao<RandomElementCollection, Long> {

    public static final String TABLENAME = "RANDOM_ELEMENT_COLLECTION";

    /**
     * Properties of entity RandomElementCollection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property NSelection = new Property(2, int.class, "nSelection", false, "N_SELECTION");
        public final static Property ShouldAllowRepeat = new Property(3, int.class, "shouldAllowRepeat", false, "SHOULD_ALLOW_REPEAT");
    };

    private DaoSession daoSession;


    public RandomElementCollectionDao(DaoConfig config) {
        super(config);
    }
    
    public RandomElementCollectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RANDOM_ELEMENT_COLLECTION' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'N_SELECTION' INTEGER NOT NULL ," + // 2: nSelection
                "'SHOULD_ALLOW_REPEAT' INTEGER NOT NULL );"); // 3: shouldAllowRepeat
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RANDOM_ELEMENT_COLLECTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RandomElementCollection entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getNSelection());
        stmt.bindLong(4, entity.getShouldAllowRepeat());
    }

    @Override
    protected void attachEntity(RandomElementCollection entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RandomElementCollection readEntity(Cursor cursor, int offset) {
        RandomElementCollection entity = new RandomElementCollection( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // nSelection
            cursor.getInt(offset + 3) // shouldAllowRepeat
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RandomElementCollection entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNSelection(cursor.getInt(offset + 2));
        entity.setShouldAllowRepeat(cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RandomElementCollection entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RandomElementCollection entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
